<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Database extends Model
{
    // HORARIOS

    const DAY_ID = [
        2, 3, 5
    ];

    const HOUR_ID = [
        6, 7, 8
    ];

    const PROFESSOR = [
        'Leticia', 'Corina', 'Vladimir Abel'
    ];

    // MATERIAS

    const SUBJECT_MATTERS = [
        'Introducción a la Programación',
        'Circuitos',
        'Taller de Sistemas Operativos',
        'Base de Datos I',
        'Elementos de Programación y Estructura de Datos',
        'Redes de Computadoras',
    ];

    // USERS

    const NAMES = [
        "ABAD",
        "ABIGAIL ELISA",
        "ABRAHAM",
        "ADRIAN",
        "ADRIANA",
        "ALAN GIOVANNI",
        "ALBA ANIER",
        "ALBERTO",
        "ALBERTO",
        "ALDAIR NELSON",
        "ALEJANDRO",
        "ALEJANDRO DIEGO",
        "ALEJANDRO",
        "ALEJANDRO",
        "ALEJANDRO PABLO",
        "ALEJANDRO",
        "ALEX",
        "ALFONSO",
        "ALVARO",
        "ANDRE",
        "ANDRES",
        "ANDRES",
        "ANDRES MATIAS",
        "ANDRES",
        "ANDRU",
        "ANGELA ANDRES",
        "ARIEL SERGIO",
        "ARIEL WILLIAM",
        "ARNOLD",
        "ARRAYA GUZMAN",
        "ARTURO",
        "BEIMAR",
        "BEIMAR",
        "BERNABE",
        "BIANCA SARAHI",
        "BRANDY",
        "BRAYAN",
        "BRIAN ARMANDO",
        "BRISA",
        "BRYAN",
        "CAMILA ADRIANA",
        "CARLA VERANICE",
        "CARLOS BRIAN",
        "CARLOS",
        "CARLOS",
        "CARLOS JOSUE",
        "CARLOS JUNIOR",
        "CAROL M.",
        "CAROLAY",
        "CECILIA",
        "CELINA",
        "CHRISTIAN DAVID",
        "CHRISTIAN JESUS",
        "CHRISTIAN",
        "CHRISTIAN VIERY",
        "CIELO CAMILA",
        "CRISTHIAN",
        "CRISTIAN",
        "CRISTIAN CHARLIE",
        "CRISTIAN",
        "CRISTOPHER",
        "CRUZ LUNA",
        "DANIEL",
        "DANIELA",
        "DARWIN",
        "DAVID",
        "DAVID CARLOS",
        "DAVID ESTEBAN",
        "DEBORA",
        "DENNIS ADRIAN",
        "DERIZ",
        "DIEGO FABRICIO",
        "DILAN ANDRES",
        "DILAN",
        "DYLAN",
        "EDDY",
        "EDGAR",
        "EDILSON",
        "EDISON",
        "EDSON GABRIEL",
        "EILEEN",
        "ELIAS",
        "EMANUEL",
        "ERICK ALEJANDRO",
        "ERICKA EMILY",
        "ESTEFANY",
        "EVELIN",
        "EVER",
        "EVERTH RODOLFO",
        "FABIAN",
        "FABRICIO",
        "FERNANDA",
        "FERNANDO",
        "FERNANDO FLORENCIO",
        "FERNANDO JOSE",
        "FERNANDO",
        "FIDEL",
        "FRANCISCO SANTIAGO",
        "GABRIELA",
        "GARCIA",
        "GARY",
        "GIULIANO NICOLA",
        "GLADYS",
        "GONZALES",
        "GROVER",
        "GUILLERMO",
        "GUSTAVO ALAN",
        "HAROL NELSON",
        "HEREDIA",
        "HUGO FERNANDO",
        "ISAI MAGDIEL",
        "ISMAEL",
        "ISRAEL GONZALO",
        "ISRAEL",
        "IVAN DOUGLAS",
        "IVAN",
        "IVAN",
        "IVELIZ ALEXANDRA",
        "JAIME CRISTIAN",
        "JAVIER EDUARDO",
        "JAVIER",
        "JAVIER",
        "JAVIER VICENTE",
        "JAZZEDT TIGLAT",
        "JESICA VANESA",
        "JHEISON",
        "JHENNIFER",
        "JHOEL MAICOL",
        "JHOEL",
        "JHONATAN",
        "JHOSEP",
        "JHOYER JOSE",
        "JOAO",
        "JONATHAN",
        "JONATHAN",
        "JONATHAN",
        "JORGE",
        "JORGE IVAN",
        "JORGE JAIR",
        "JOSE ARMANDO",
        "JOSE",
        "JOSE MAURICIO",
        "JOSE",
        "JOSELYNNE",
        "JOSHUA GABRIEL",
        "JOSUE",
        "JOSUE",
        "JOSUE",
        "JUAN DEYBI",
        "JUAN EDUARDO",
        "JUAN GABRIEL",
        "JUAN",
        "JULIO ALVARO",
        "JULIO CESAR",
        "JULIO RENE",
        "KAREN",
        "KATERIN",
        "KATHERINE",
        "KATHERINE",
        "KATRINA DANORA",
        "KEVIN",
        "KEVIN ERICK",
        "KEVIN JONATAN",
        "KEVIN RAUL",
        "KEVIN RODRIGO",
        "KEVIN",
        "KEVIN",
        "LEONEL",
        "LIMBERT",
        "LIZBETH",
        "LIZBETH",
        "LUIS ALEJANDRO",
        "LUIS ANTONIO",
        "LUIS",
        "LUIS VEIDMAR",
        "LUIYARD MARCELO",
        "MADAI",
        "MARCELO",
        "MARCOS JULIO",
        "MARIA ANDREA",
        "MARIA ELENA",
        "MARIANA NATHALY",
        "MARIO ANTONIO",
        "MAURICIO",
        "MAURICIO DAVID",
        "MAURICIO",
        "MAURICIO OSCAR",
        "MAURICIO",
        "MAURICIO",
        "MAYDER",
        "MIGUEL ANGEL",
        "MIGUEL TOMAS",
        "MORALES CALLEJAS",
        "NANER",
        "NAOMI",
        "NATHALY",
        "NEK BRAYAN",
        "NELSON JAVIER",
        "NICOLE",
        "NICOLE MELANIA",
        "NICOLE",
        "NINETH",
        "NOE",
        "NOEL",
        "NUMBELA ROJAS",
        "OLIVER",
        "OLIVER",
        "OMAR ANDRES",
        "OSCAR",
        "OSCAR",
        "PABLO ROMAN",
        "PABLO SAUL",
        "PAOLA ANDREA",
        "PARRA SUZANO",
        "POLETH",
        "RASHEL EYMI",
        "RAUL",
        "RAUL",
        "RICARDO",
        "RICARDO JAVIER",
        "RIMER SAUL",
        "RODRIGO",
        "RODRIGO",
        "RODRIGO",
        "RODRIGUEZ",
        "ROGER RUDY",
        "ROLANDO",
        "ROLY",
        "ROMARIO",
        "ROMEL ALAIN",
        "ROSARIO",
        "SAMUEL ALEX",
        "SAMUEL",
        "SAMUEL",
        "SANTIAGO EDWING",
        "SARINA",
        "SELENA",
        "SERGIO",
        "SHIRLEY EDITH",
        "SOFIA",
        "SOFIA",
        "ULISES",
        "VALERIA ADRIANA",
        "VANESSA ESTHER",
        "VEYMAR",
        "VEYMAR",
        "VIANCA",
        "VILMER",
        "WALDO",
        "WENDDY MARIEL",
        "WENDY",
        "WENDY",
        "WILDER",
        "WILFREDO",
        "WILLMAR",
        "WILSON",
        "YESUA",
    ];

    const FIRST_NAME = [
        "CHAMBI",
        "GALZIN",
        "ILLANES",
        "CAMARA",
        "VELARDE",
        "MORA",
        "MONTENEGRO",
        "HUARACHI",
        "MAMANI",
        "TORREZ",
        "CHAVEZ",
        "SAAVEDRA",
        "FUENTES",
        "MONTANO",
        "CONDO",
        "SEJAS",
        "PACA",
        "MERCADO",
        "MOLINA",
        "ALDUNATE",
        "BRAVO",
        "GARCIA",
        "ALVAREZ",
        "TORRICO",
        "X.",
        "SALVATIERRA",
        "RODRIGUEZ",
        "MEJIA",
        "COPA",
        "EDUARDO",
        "CAMACHO",
        "ARISPE",
        "CABRERA",
        "CATARI",
        "FERNANDEZ",
        "REQUE",
        "BUSTILLOS",
        "SUAREZ",
        "ROJAS",
        "VASQUEZ",
        "CESPEDES",
        "ARGOTE",
        "REVOLLO",
        "DANIEL",
        "FERNANDO",
        "VASQUEZ",
        "MANGUDO",
        "SEJAS",
        "VERA",
        "VERGARA",
        "SERRANO",
        "SALVATIERRA",
        "LLANOS",
        "MANUEL",
        "MOLLO",
        "FLORES",
        "GRAGEDA",
        "ARANDO",
        "APAZA",
        "TAPIA",
        "APAZA",
        "LEONARDO",
        "PEREZ",
        "CLAROS",
        "GARCIA",
        "BORIZZ",
        "PEREZ",
        "ORELLANA",
        "MARTINEZ",
        "PARI",
        "CHOQUE",
        "SANDOVAL",
        "VELARDE",
        "ANTEZANA",
        "CESPEDES",
        "QUISPE",
        "FERRUFINO",
        "ALIAGA",
        "FLORES",
        "CESPEDES",
        "ELIZA",
        "CANAVIRI",
        "QUISPE",
        "QUIROZ",
        "CAMACHO",
        "RODRIGUEZ",
        "ELIANA",
        "COCA",
        "COPA",
        "PENARRIETA",
        "HUARI",
        "AGUILAR",
        "CALLE",
        "AYAVIRI",
        "DAZA",
        "RODRIGUEZ",
        "UGARTE",
        "CARVALLO",
        "COCA",
        "SOLIZ",
        "ROCA",
        "HUANCA",
        "BORRAZ",
        "YAHUILA",
        "CHURA",
        "ROJAS",
        "MONTANO",
        "ARCOS",
        "ALEJANDRO",
        "CARI",
        "QUISPE",
        "PERALTA",
        "OROSCO",
        "RODRIGUEZ",
        "ALARCON",
        "FLORES",
        "GOMEZ",
        "AYALA",
        "GARCIA",
        "LLANOS",
        "FILIGRANA",
        "FILIGRANA",
        "GARCIA",
        "MONTANO",
        "BORDA",
        "LEON",
        "FARJURI",
        "MURILLO",
        "ROJAS",
        "CUENCA",
        "TINTA",
        "OCANA",
        "CARPIO",
        "MONTANO",
        "ALA",
        "MAYRE",
        "BORGES",
        "LOBO",
        "CONDORI",
        "MENECES",
        "CACERES",
        "DEL CASTILLO",
        "QUIROZ",
        "BELEN",
        "MURILLO",
        "FUENTES",
        "INTURIAS",
        "LARA",
        "GAMBOA",
        "SARAVIA",
        "SALAZAR",
        "I.",
        "IGLESIAS",
        "PAYA",
        "CAMACHO",
        "CHOQUECALLATA",
        "OJEDA",
        "ORTIZ",
        "ZAMBRANA",
        "ALBORTA",
        "DANNY",
        "AGUILAR",
        "YANA",
        "URENA",
        "PERALTA",
        "VILLANUEVA",
        "VILLARROEL",
        "VELEZ",
        "ALCONZ",
        "CAYETANO",
        "PACARI",
        "PERES",
        "CORRALES",
        "HUARINA",
        "CHOQUE",
        "CLAROS",
        "FLORES",
        "CHOQUE",
        "RAMOS",
        "PELAEZ",
        "BERNABE",
        "VILLARROEL",
        "MURILLO",
        "COCA",
        "ORTUNO",
        "HUAYTA",
        "CRESPO",
        "RAMOS",
        "ZABALAGA",
        "SAAVEDRA",
        "VILLCA",
        "AGUILAR",
        "SOLEDAD",
        "PURI",
        "PRADO",
        "GARCIA",
        "FERRUFINO",
        "CRUZ",
        "DEL CASTILLO",
        "CRUZ",
        "ROJAS",
        "ADELA",
        "ESPINOZA",
        "GARCIA",
        "VANGELI",
        "CHIRI",
        "VILLARROEL",
        "SELAYA",
        "ANDRE",
        "ORDONEZ",
        "YAVE",
        "MAGUINA",
        "VILLCA",
        "LESLY",
        "TORDOYA",
        "PARRA",
        "FERNANDEZ",
        "TERRAZAS",
        "GONGORA",
        "UDAETA",
        "ROSA",
        "GUACHALLA",
        "OLIVERA",
        "QUENA",
        "GUARAYO",
        "ESPINOZA",
        "GUILLE",
        "MONTECINOS",
        "RAMOS",
        "MEDINA",
        "GUAMAN",
        "MONTANO",
        "BORDA",
        "COPA",
        "BRAVO",
        "CORIA",
        "SANTA",
        "VEIZAGA",
        "ROMERO",
        "DANIELA",
        "SILVESTRE",
        "MALDONADO",
        "CABRERA",
        "FLORES",
        "HINOJOSA",
        "HINOJOSA",
        "MAMANI",
        "VILLARROEL",
        "CRUZ",
        "ROMERO",
        "ALVAREZ",
        "RODRIGUEZ",
        "MERIDA",
        "NESTOR",
        "HUARACHI",
        "CESPEDES",
        "JIMENEZ"
    ];

    const SECOND_NAME = [
        "LEON",
        "BAZOALTO",
        "FLORES",
        "REQUE",
        "C.",
        "VARGAS",
        "ANGULO",
        "X.",
        "X.",
        "QUIROGA",
        "U.",
        "ARTEAGA",
        "X.",
        "CAYOLA",
        "URENA",
        "ALCOCER",
        "MENESES",
        "V.",
        "VILLAMOR",
        "GUZMAN",
        "AGUILAR",
        "QUISPE",
        "NUNEZ",
        "X.",
        "X.",
        "CABRERA",
        "MILAN",
        "LAZARTE",
        "FLORES",
        "JOSUE",
        "MAMANI",
        "ARNEZ",
        "HUANCA",
        "COLQUE",
        "QUISPE",
        "COCA",
        "ZUBIETA",
        "AGUIRRE",
        "BANG",
        "MALDONADO",
        "VILLENA",
        "PINTO",
        "VILLARROEL",
        "JUCHASARA",
        "ROJAS",
        "HUANCA",
        "BETANCUR",
        "DELGADILLO",
        "BORDA",
        "ZEBALLOS",
        "X.",
        "CLAROS",
        "MENDOZA",
        "CAMACHO",
        "GONZALES",
        "VERASTEGUI",
        "COTRINA",
        "QUECANA",
        "GUTIERREZ",
        "LOPEZ",
        "CARBALLO",
        "ALVARO",
        "GARCIA",
        "X.",
        "AREBALO",
        "SANTOS",
        "CHOQUE",
        "GUTIERREZ",
        "BURGOS",
        "LIMACHI",
        "JIMENEZ",
        "CHUMACERO",
        "ARISPE",
        "X.",
        "BENAVIDES",
        "RODRIGUEZ",
        "GARCIA",
        "GARCIA",
        "X.",
        "DELGADILLO",
        "PACARA",
        "CHOQUEVILLCA",
        "X.",
        "GIL",
        "GARCIA",
        "HIDALGO",
        "SOLIS",
        "QUIROZ",
        "ALDABA",
        "X.",
        "SILES",
        "VILLALOBOS",
        "GONZALES",
        "GAMARRA",
        "YARHUI",
        "MORALES",
        "ARRATIA",
        "LAZO",
        "COSSIO",
        "GISELLE",
        "VALENCIA",
        "VERDUGUEZ",
        "HUIZA",
        "ALISON",
        "FLORES",
        "BECERRA",
        "ARGOTE",
        "TERRAZAS",
        "X.",
        "CAZAS",
        "PEREZ",
        "FERNANDEZ",
        "ZEBALLOS",
        "IMPA",
        "CASTRO",
        "CALLE",
        "ORELLANA",
        "LOPEZ",
        "VINO",
        "GUZMAN",
        "X.",
        "X.",
        "PADILLA",
        "O.",
        "MORALES",
        "X.",
        "SAAVEDRA",
        "COCA",
        "VALDEZ",
        "PILCO",
        "MANCILLA",
        "TICONA",
        "ROCHA",
        "X.",
        "ZURITA",
        "NOGUERA",
        "REYES",
        "ORTUNO",
        "REQUENA",
        "SOLIZ",
        "ARAMAYO",
        "VALDIVIA",
        "X.",
        "TORRICO",
        "ROCHA",
        "CUAQUIRA",
        "S.",
        "PAQUI",
        "MARCA",
        "MIRANDA",
        "V.",
        "ROMERO",
        "HUARACHI",
        "ARGOTE",
        "GARCIA",
        "X.",
        "POZO",
        "MAMANI",
        "CONTRERAS",
        "DELGADO",
        "POMA",
        "ARISPE",
        "QUISPE",
        "VIDAL",
        "AYLLON",
        "RIVAS",
        "CHAUCA",
        "FERREL",
        "TAPIA",
        "MIRANDA",
        "MAMANI",
        "SANTOS",
        "ALBARRACIN",
        "TANGO",
        "DURAN",
        "PEREYRA",
        "MODRAGON",
        "CUELLAR",
        "CACERES",
        "CRUZ",
        "CHUCUTEA",
        "VARGAS",
        "ZEBALLOS",
        "NAVARRO",
        "AHENKE",
        "VILLANUEVA",
        "MONTANO",
        "X.",
        "X.",
        "VEIZAGA",
        "MINAYA",
        "SARAVIA",
        "NATALIS",
        "MAMANI",
        "HINOJOSA",
        "X.",
        "TOLA",
        "MONTANO",
        "VALDIVIA",
        "GONZALES",
        "ZAMBRANA",
        "PINAYA",
        "FLORES",
        "MEJIA",
        "JAIRO",
        "ZAMBRANA",
        "CAYPA",
        "ANTELO",
        "RODRIGUEZ",
        "PINTO",
        "MAGNE",
        "APAZA",
        "MAIZA",
        "MELINA",
        "MEJIA",
        "LOPEZ",
        "X.",
        "GARCIA",
        "VASQUEZ",
        "LARRAIN",
        "HERRERA",
        "COSSIO",
        "NAVIA",
        "CALIZAYA",
        "JESSICA",
        "RIOS",
        "ESCALERA",
        "GARCIA",
        "RAMIREZ",
        "VELASCO",
        "ROMAN",
        "FERNANDEZ",
        "CABALLERO",
        "CAMACHO",
        "B.",
        "GUTIERREZ",
        "CRUZ",
        "MUNOZ",
        "QUISPE",
        "COVARRUBIAS",
        "CRUZ",
        "ESPEJO",
        "CHAVARRIA",
        "MONTANO",
        "JUAN",
        "JUAN",
        "RAMOS",
        "SANCHEZ",
        "ZURITA",
        "NINA",
        "DAVILA",
        "ANGULO",
        "ARISTA",
        "MAMANI",
        "GARCIA",
        "R.",
        "GONZALES"
    ];

    // INSCRIPCIONES

    const BLOCK_SCHEDULES = [
        4,
        3,
        7,
        9,
        1,
        5,
        3,
        6,
        3,
        2,
        7,
        8,
        2,
        6,
        7,
        6,
        5,
        8,
        7,
        5,
        2,
        9,
        9,
        5,
        4,
        3,
        1,
        1,
        1,
        3,
        6,
        5,
        5,
        2,
        5,
        7,
        4,
        8,
        2,
        5,
        6,
        1,
        5,
        4,
        3,
        2,
        6,
        7,
        8,
        1,
        4,
        4,
        7,
        9,
        8,
        6,
        4,
        5,
        1,
        7,
        8,
        1,
        3,
        4,
        8,
        9,
        6,
        8,
        7,
        7,
        4,
        2,
        8,
        7,
        9,
        9,
        6,
        2,
        4,
        3,
        6,
        8,
        5,
        8,
        8,
        5,
        5,
        5,
        8,
        7,
        3,
        7,
        8,
        5,
        4,
        5,
        5,
        5,
        7,
        9,
        1,
        1,
        8,
        5,
        2,
        2,
        7,
        7,
        7,
        9,
        3,
        2,
        5,
        5,
        1,
        2,
        2,
        8,
        7,
        7,
        7,
        9,
        8,
        7,
        9,
        2,
        4,
        2,
        2,
        2,
        1,
        4,
        8,
        6,
        9,
        2,
        6,
        4,
        1,
        8,
        6,
        8,
        2,
        1,
        8,
        7,
        2,
        3,
        9,
        5,
        3,
        1,
        3,
        9,
        7,
        3,
        1,
        2,
        8,
        8,
        3,
        7,
        1,
        2,
        8,
        7,
        2,
        9,
        8,
        6,
        2,
        7,
        4,
        4,
        2,
        8,
        1,
        5,
        2,
        7,
        4,
        1,
        7,
        3,
        3,
        2,
        1,
        5,
        5,
        4,
        7,
        7,
        8,
        5,
        3,
        9,
        1,
        9,
        7,
        7,
        1,
        1,
        4,
        1,
        4,
        6,
        3,
        2,
        8,
        4,
        2,
        1,
        1,
        8,
        4,
        1,
        4,
        3,
        8,
        5,
        1,
        9,
        2,
        1,
        8,
        1,
        2,
        4,
        7,
        1,
        7,
        9,
        5,
        6,
        2,
        4,
        8,
        9,
        5,
        4,
        5,
        2,
        8,
        5,
        2,
        5,
        5,
        8,
        1,
        1,
        9,
        6,
        1,
        5,
        2,
        5,
        1,
    ];

    const STUDENT_GROUP = [
        10,
        10,
        2,
        7,
        2,
        2,
        7,
        10,
        7,
        7,
        7,
        2,
        2,
        10,
        2,
        10,
        2,
        10,
        2,
        2,
        7,
        7,
        2,
        7,
        10,
        7,
        2,
        10,
        2,
        10,
        10,
        10,
        2,
        7,
        10,
        10,
        7,
        2,
        2,
        2,
        7,
        10,
        2,
        2,
        10,
        7,
        10,
        10,
        10,
        2,
        10,
        10,
        2,
        10,
        10,
        7,
        10,
        2,
        2,
        10,
        2,
        10,
        10,
        10,
        10,
        7,
        7,
        10,
        7,
        2,
        7,
        2,
        7,
        2,
        7,
        2,
        10,
        2,
        7,
        10,
        10,
        7,
        2,
        7,
        2,
        2,
        10,
        2,
        2,
        10,
        7,
        2,
        7,
        10,
        2,
        2,
        10,
        2,
        2,
        2,
        2,
        10,
        10,
        2,
        7,
        2,
        7,
        2,
        7,
        7,
        10,
        7,
        2,
        10,
        2,
        7,
        2,
        2,
        10,
        2,
        10,
        2,
        7,
        7,
        2,
        7,
        10,
        10,
        2,
        10,
        10,
        7,
        10,
        10,
        2,
        2,
        7,
        7,
        2,
        10,
        7,
        10,
        7,
        7,
        10,
        10,
        2,
        10,
        2,
        2,
        10,
        10,
        10,
        2,
        2,
        7,
        2,
        2,
        2,
        2,
        7,
        2,
        7,
        2,
        2,
        10,
        10,
        2,
        10,
        10,
        2,
        2,
        10,
        7,
        10,
        2,
        2,
        2,
        2,
        10,
        2,
        10,
        10,
        7,
        7,
        2,
        2,
        7,
        2,
        7,
        2,
        2,
        2,
        2,
        10,
        2,
        2,
        10,
        2,
        2,
        2,
        10,
        7,
        2,
        10,
        10,
        7,
        2,
        7,
        7,
        7,
        10,
        2,
        2,
        2,
        2,
        7,
        7,
        10,
        2,
        10,
        10,
        7,
        2,
        2,
        7,
        10,
        7,
        2,
        10,
        7,
        2,
        2,
        7,
        10,
        10,
        10,
        7,
        7,
        10,
        2,
        7,
        7,
        10,
        10,
        10,
        2,
        2,
        2,
        10,
        2,
        10,
        2,
        7,
        2,
        10,
        10,
    ];

    // GUIA PRÁCTICA

    const TASKS = [
        'PracticaSaludador',
        'Clases',
        'ClasesConstructores',
        'ImplementandoMetodos',
        'ImplementandoMetodos',
        'InteraccionObjetos',
        'InteraccionObjetos',
        'InteraccionObjetos',
        'InteraccionObjetos',
        'Colecciones',
        'ColeccionesCadenas',
        'ColeccionesCadenas',
        'ArreglosCadenas',
        'Herencia',
        'HerenciaTres'
    ];

    const NAME_TASKS = [
        'Sesion1_PracticaSaludador.pdf',
        'Sesion2_Clases.pdf',
        'Sesion3_ClasesConstructores.pdf',
        'Sesion4_ImplementandoMetodos.pdf',
        'Sesion5_ImplementandoMetodos.pdf',
        'Sesion6_InteraccionObjetos.pdf',
        'Sesion7_InteraccionObjetos.pdf',
        'Sesion8_InteraccionObjetos.pdf',
        'Sesion9_InteraccionObjetos.pdf',
        'Sesion10.rar',
        'Sesion11_ColeccionesCadenas.pdf',
        'Sesion12_ColeccionesCadenas.pdf',
        'Sesion13_ArreglosCadenas.pdf',
        'Sesion14_Herencia.pdf',
        'Sesion15_HerenciaTres.pdf',
    ];

    // TAREAS DE ESTUDIANTES

    const NUMBER_TASKS = [9, 9, 9, 9, 10, 9, 8, 12];
    const STUDENTS_ID = [123, 197, 183, 121, 216, 134, 162, 248];

    const TASKS_STUDENT_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    const TASKS_STUDENT_2 = [1, 2, 3, 4, 5, 6, 7, 9, 10];
    const TASKS_STUDENT_3 = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    const TASKS_STUDENT_4 = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    const TASKS_STUDENT_5 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];//
    const TASKS_STUDENT_6 = [1, 2, 3, 4, 5, 6, 7, 9, 11];
    const TASKS_STUDENT_7 = [1, 2, 3, 4, 5, 6, 7, 8];
    const TASKS_STUDENT_8 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

    const TASK_NAME_STUDENT_1 = [
        'PrimerProyecto.rar',
        'tarea2.rar',
        'tarea3.rar',
        'tarea4.rar',
        'tarea5.rar',
        'tarea6.rar',
        'ejercicio7.rar',
        'ejercicio8.rar',
        'ejercicio9.rar'
    ];
    const TASK_NAME_STUDENT_2 = [
        'SESION 1.rar',
        'SESION 2.rar',
        'SESION 3.rar',
        'SESION 4.rar',
        'SESION 5.rar',
        'SESION 6.rar',
        'SESION 7.rar',
        'SESION 9.rar',
        'SESION 10.rar'
    ];
    const TASK_NAME_STUDENT_3 = [
        'Semana1.rar',
        'Semana2.rar',
        'Semana3.rar',
        'Semana4.rar',
        'Semana5.rar',
        'Semana6.rar',
        'Semana7.rar',
        'Semana8.rar',
        'Semana9.rar'
    ];
    const TASK_NAME_STUDENT_4 = [
        'semana 1.rar',
        'semana 2.rar',
        'semana 3.rar',
        'semana 4.rar',
        'semana 5.rar',
        'semana 6.rar',
        'semana 7.rar',
        'semana 8.rar',
        'semana 9.rar'
    ];
    const TASK_NAME_STUDENT_5 = [
        'sesion1.rar',
        'sesion2.rar',
        'sesion3.rar',
        'sesion4.rar',
        'sesion5.rar',
        'sesion6.rar',
        'sesion7.rar',
        'sesion8.rar',
        'sesion9.rar',
        'sesion10.rar'
    ];//
    const TASK_NAME_STUDENT_6 = [
        'semana 1.rar',
        'semana 2.rar',
        'semana 3.rar',
        'semana 4.rar',
        'semana 5.rar',
        'semana 6.rar',
        'semana 7.rar',
        'semana 9.rar',
        'semana 9.rar'
    ];
    const TASK_NAME_STUDENT_7 = [
        'SESION 1.rar',
        'SESION 2.rar',
        'SESION 3.rar',
        'SESION 4.rar',
        'SESION 5.rar',
        'SESION 6.rar',
        'SESION 7.rar',
        'SESION 8.rar'
    ];
    const TASK_NAME_STUDENT_8 = [
        'sesion1.rar',
        'sesion2.rar',
        'sesion3.rar',
        'sesion4.rar',
        'sesion5.rar',
        'sesion6.rar',
        'sesion7.rar',
        'sesion8.rar',
        'sesion9.rar',
        'sesion10.rar',
        'sesion11.rar',
        'sesion12.rar'
    ];

    const TASK_DESCRIPTION = [
        'Completo el ejercicio ',
        'Hizo el ejercicio ',
        'Funcionó ',
        'Termnado ',
    ];
}
